Material values:
- hard_surface
- brickwork
- rough_concrete
- ceramic_tiles
- concrete_floor
- plasterboard
- glass_window
- wood_1.6cm
- audience_floor
- stage_floor
- wooden_door
- carpet_cotton
- carpet_thin
- curtains_velvet
- studio_curtains
- chairs_wooden
- audience_orchestra_choir
- facing_brick
- ceiling_plasterboard
- theatre_audience
- anechoic
Room:
  floor: 1
  height: 10000
  humadity: 0
  length: 10000
  microphones: []
  sources: []
  temperature: 0
  walls: 20
  width: 10000
Simulation parameters:
  SNR: 0
  air_absorbtion: true
  fs: 16000
  max_order: 1
  ray_tracing: false
  reference_microphone: 0
  reverberation_time: 0
Sources:
  keys:
    - [Source1, 0]
    - [Source2, 1]
  index of keys: 2     #number
  sources:
    0:
      form: 0
      functional_form:
        amplitude: 5000
        fs: 11000
        frequency: 5000
        time: 5
        phase: 0
        x: 5000
        y: 10
        z: 10
        muted: 0
      wav file:
        filename: ''
        fs: 0
        t_start: 0
        t_end: 0
        time: 0
        x: 5000
        y: 10
        z: 10
        muted: 0
    1:
      form: 1
      functional_form:
        amplitude: 0
        fs: 0
        frequency: 0
        phase: 0
        time: 0
        x: 5000
        y: 9990
        z: 10
        muted: 0
      wav file:
        filename: C:\passing-car-and-urban-ambience.wav
        fs: 16000
        t_start: 0
        t_end: 5
        time: 5
        x: 5000
        y: 9990
        z: 10
        muted: 0
Microphones:
  keys:
    - [ Microphone1, 0 ]
  index of keys: 1
  microphones:
    0:
      x: 20
      y: 20
      z: 20
      muted: 0
