Material values:
- hard_surface
- brickwork
- rough_concrete
- ceramic_tiles
- concrete_floor
- plasterboard
- glass_window
- wood_1.6cm
- audience_floor
- stage_floor
- wooden_door
- carpet_cotton
- carpet_thin
- curtains_velvet
- studio_curtains
- chairs_wooden
- audience_orchestra_choir
- facing_brick
- ceiling_plasterboard
- theatre_audience
- anechoic
Simulation_Space:
  floor: 1
  height: 10000
  humadity: 0
  length: 10000
  microphones: []
  sources: []
  temperature: 0
  walls: 20
  width: 10000
Simulation parameters:
  SNR: 0
  air_absorbtion: true
  fs: 16000
  max_order: 1
  ray_tracing: false
  reference_microphone: 0
  reverberation_time: 0
Sources:
  ID: [0, 1]
  count: 2
  index of ids: 1     #ids
  sources:
    0:
      name: Source1
      form: 0
      functional_form:
        x: 5000
        y: 10
        z: 10
        muted: 0
        duration: 5
        frequency_parameters:
          freq_ids: [0, 1]
          index: 1
          parameters:
            0:
              name: F1
              frequency: 5000
              amplitude: 5000
              phase: 0
            1:
              name: F2
              frequency: 7000
              amplitude: 8000
              phase: 2

      wav file:
        filename: ''
        t_start: 0
        t_end: 0
        x: 5000
        y: 10
        z: 10
        muted: 0
    1:
      name: Source2
      form: 1
      functional_form:
        x: 2000
        y: 5000
        z: 3000
        muted: 0
        duration: 5
        frequency_parameters:
          freq_ids: [0]
          index: 0
          parameters:
            0:
              name: F1
              frequency: 5000
              amplitude: 5000
              phase: 0
      wav file:
        filename: C:\passing-car-and-urban-ambience.wav
        t_start: 0
        t_end: 5
        time: 5
        x: 5000
        y: 9990
        z: 10
        muted: 0
Microphones:
  ID: [0]
  count: 1
  index of ids: 0
  microphones:
    0:
      name: Microphone1
      filepath: D:\Simulation results\Microphone1.wav
      parameters:
        x: 2000
        y: 2000
        z: 2000
        muted: 0

