Material values:
- hard_surface
- brickwork
- rough_concrete
- ceramic_tiles
- concrete_floor
- plasterboard
- glass_window
- wood_1.6cm
- audience_floor
- stage_floor
- wooden_door
- carpet_cotton
- carpet_thin
- curtains_velvet
- studio_curtains
- chairs_wooden
- audience_orchestra_choir
- facing_brick
- ceiling_plasterboard
- theatre_audience
- anechoic
Room:
  length: 10000
  width: 10000
  height: 10000
  sources: []
  microphones: []
  temperature: 0
  humadity: 0
  walls: 20
  floor: 1

Simulation parameters:
  fs: 16000
  max_order: 1
  reverberation_time: 0
  reference_microphone: 0
  SNR: 0
  air_absorbtion: True
  ray_tracing: False

Sources:
  Source1:
    form: 0
    functional_form:
      amplitude: 5000
      fs: 11000
      frequency: 5000
      time: 5
      phase: 0
      x: 5000
      y: 10
      z: 10
      muted: 0
    wav file:
      filename: ''
      fs: 0
      t_start: 0
      t_end: 0
      time: 0
      x: 5000
      y: 10
      z: 10
      muted: 0
  Source2:
    form: 1
    functional_form:
      amplitude: 0
      fs: 0
      frequency: 0
      phase: 0
      time: 0
      x: 5000
      y: 9990
      z: 10
      muted: 0
    wav file:
      filename: C:\passing-car-and-urban-ambience.wav
      fs: 16000
      t_start: 0
      t_end: 5
      time: 5
      x: 5000
      y: 9990
      z: 10
      muted: 0
microphones:
  mic1:
    x: 20
    y: 20
    z: 20
    muted: 0





